### ISSUE TITLE
Steering amount in axle definition should be in radians

### ISSUE THREAD

**Issue by mirkobulaja-avl** [arauschert/OSC-ALKS-scenarios#25]
This looks like a value in degrees, while the standard specifies it should be in radians.
`<FrontAxle maxSteering="30" wheelDiameter="0.8" trackWidth="1.68" positionX="2.98" positionZ="0.4" />`

> maxSteering | double | 1..1 | XSDattribute | Maximum steering angle which can be performed by the wheels on this axle. Unit: rad; Range: [0;PI]

**Comment by arauschert** [comment]
Thanks for pointing that out! We´ll change that.
