### ISSUE TITLE
Add a solution for running on Linux

### ISSUE THREAD

**Issue by smipi1** [arauschert/OSC-ALKS-scenarios#27]
Most developers working on Automated Driving stacks are using Linux as their desktop operating system because 'everything just works'. Would it be possible to also add instructions and support for running on Linux x86_64?

**Comment by jdsika** [comment]
it is funny that you ask because we thought about it and said "the linux guys know it anyway let's just do windows".
I will add it for the sake of completeness!

**Comment by smipi1** [comment]
You are right! I figured it out. But I will send you a pull request anyway. ;-)

**Comment by arauschert** [comment]
We've added a description how to run the scenarios on Linux with CARLA with the above PR.
