### ISSUE TITLE
esmini 2.0

### ISSUE THREAD

**Issue by eknabevcc** [arauschert/OSC-ALKS-scenarios#28]
Tomorrow (Friday) afternoon is planned release of esmini 2.0. Most significant news is support of OSC controller concept. A positive side effect is that we could reduce the palette of "applications". As you also pointed out, the interactive, external and hybrid modes are now implemented as controllers instead of specific application features. 
Now, this led us to take the opportunity and do some desired restructuring and renaming of esmini modules. So far so good. Downside is broken backward compatibility.

There are two changes affecting your project:
1. "EgoSimulator" renamed to "esmini"
2. Trails is off by default. Instead a single argument "--trails" will turn them on. So the script option "--trails off" will actually turn them on and the "off" part will be parsed as an unknown argument and put a warning on stdout. However, esmini will run nonetheless, with trails. 

First issue I've solved short term by providing a copy of esmini(.exe) named EgoSimulator(.exe). Let's say that we provide this copy during a deprecation period of a few releases. 
Second issue is not a showstopper. Actually I find the trails useful since it gives a sense of speed and motion forward along the OpenDRIVE features lines. So, even though not critical, my suggestion is to eventually change into "--trails". 

I've checked all 15 ALKS scenarios of yours. As far as I can see, they run all fine in esmini 2.0 BETA. 

This is a heads-up in order to dampen the surprise of esmini 2.0 release tomorrow afternoon. [Link to a beta version ](https://drive.google.com/file/d/1YE_XnTv5ImEplZzfuuuShaMKzF4ZiGz5/view?usp=sharing)in case you would like to test before release.

Let me know if you see any issues that I did not think of!

**Comment by arauschert** [comment]
Thanks a lot for letting us know!
We´ll update the scripts accordingly and prepare a new release for esmini 2.0 once it´s out.
We´ll also check out how the new controller support works.
