### ISSUE TITLE
Usage of environment variables / Missing options to manually set filepath in "run_Scenarios.bat"

### ISSUE THREAD

**Issue by LudwigFriedmann** [arauschert/OSC-ALKS-scenarios#31]
While I see the benefit in using environment variables in "run_Sceanrios.bat", defining or changing them requires  administrative rights on Windows machines.

The usability of the script could be improved by adding options that allow the user to set the directory path manually,
e.g. do a
SET ESMINI=My\\Path\\to\\esmini\\binary\\directory
or a
SET OPENPASS=My\\Path\\to\\openpass\\binary\\directory

A script for linux based systems (as reqested in #27 ), should provide the same functionality ... ;)

**Comment by arauschert** [comment]
Thanks for the comment. You can also define and change environment variables for each user on a windows machine, which doesn´t require administrative rights. That´s how I did it. Please try and let me know, if it works for you.

**Comment by LudwigFriedmann** [comment]
Sorry I missed that user specific environment variables were moved in Win10. I thought they simply no longer exist :D Nevertheless, specifying the path manually may be helpful ...

**Comment by arauschert** [comment]
Agreed with Ludwig to close the issue since a suitable solution exists.
